/*
 * AllInOne Banner - Content Slider v3.4
 *
 * Copyright 2012-2017, LambertGroup
 * 
*/


(function(c){function G(a,b,e){e.responsive&&(newCss="",-1!=a.css("font-size").lastIndexOf("px")?(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("px")),newCss+="font-size:"+fontSize/(e.origWidth/e.width)+"px;"):-1!=a.css("font-size").lastIndexOf("em")&&(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("em")),newCss+="font-size:"+fontSize/(e.origWidth/e.width)+"em;"),-1!=a.css("line-height").lastIndexOf("px")?(lineHeight=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("px")),
newCss+="line-height:"+lineHeight/(e.origWidth/e.width)+"px;"):-1!=a.css("line-height").lastIndexOf("em")&&(lineHeight=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("em")),newCss+="line-height:"+lineHeight/(e.origWidth/e.width)+"em;"),a.wrapInner('<div class="newFS" style="'+newCss+'" />'));var g=a.attr("data-final-left"),f=a.attr("data-final-top");e.responsive&&(g=parseInt(g/(e.origWidth/e.width),10),f=parseInt(f/(e.origWidth/e.width),10));e=1;1==b.isVideoPlaying&&(e=0);a.animate({opacity:e,
left:g+"px",top:f+"px"},1E3*a.attr("data-duration"),function(){1==b.isVideoPlaying&&c(b.currentImg.attr("data-text-id")).children().css("opacity",0)})}function K(a,b,e,g){c(a.currentImg.attr("data-text-id")).css("display","block");e=c(a.currentImg.attr("data-text-id")).children();var f=0;currentText_arr=[];e.each(function(){currentText_arr[f]=c(this);var e=currentText_arr[f].attr("data-initial-left"),g=currentText_arr[f].attr("data-initial-top");b.responsive&&(e=parseInt(e/(b.origWidth/b.width),10),
g=parseInt(g/(b.origWidth/b.width),10));currentText_arr[f].css({left:e+"px",top:g+"px",opacity:parseInt(currentText_arr[f].attr("data-fade-start"),10)/100});var z=currentText_arr[f];setTimeout(function(){G(z,a,b)},1E3*currentText_arr[f].attr("data-delay"));f++})}function z(a,b,e,g,f,v,m,D,A,w,t){var l=!0;if(!e.loop&&b.current_img_no+a>=g||!e.loop&&0>b.current_img_no+a)l=!1;l&&!b.slideIsRunning&&(c(".newFS",w).contents().unwrap(),b.arcInitialTime=(new Date).getTime(),b.timeElapsed=0,e.showCircleTimer&&
(b.ctx.clearRect(0,0,b.canvas.width,b.canvas.height),b.ctx.beginPath(),b.ctx.globalAlpha=e.behindCircleAlpha/100,b.ctx.arc(e.circleRadius+2*e.circleLineWidth,e.circleRadius+2*e.circleLineWidth,e.circleRadius,0,2*Math.PI,!1),b.ctx.lineWidth=e.circleLineWidth+2,b.ctx.strokeStyle=e.behindCircleColor,b.ctx.stroke(),b.ctx.beginPath(),b.ctx.globalAlpha=e.circleAlpha/100,b.ctx.arc(e.circleRadius+2*e.circleLineWidth,e.circleRadius+2*e.circleLineWidth,e.circleRadius,0,0,!1),b.ctx.lineWidth=e.circleLineWidth,
b.ctx.strokeStyle=e.circleColor,b.ctx.stroke()),b.slideIsRunning=!0,b.previous_current_img_no=b.current_img_no,c(b.currentImg.attr("data-text-id")).css("display","none"),c(f[b.current_img_no]).removeClass("bottomNavButtonON"),t.css("display","none"),b.current_img_no=b.current_img_no+a>=g?0:0>b.current_img_no+a?g-1:b.current_img_no+a,c(f[b.current_img_no]).addClass("bottomNavButtonON"),b.currentImg=c(v[b.current_img_no]),A.animate({left:-1*b.current_img_no*e.width+"px"},800,"easeOutQuad",function(){b.slideIsRunning=
!1;"true"==c(v[b.current_img_no]).attr("data-video")&&t.css("display","block");"true"==c(v[b.previous_current_img_no]).attr("data-video")&&(c("#contentHolderUnit_"+b.previous_current_img_no,w).html(c(v[b.previous_current_img_no]).html()),H(b.previous_current_img_no,b,e,v,w,m,D));K(b,e,m,D);0<e.autoPlay&&1<g&&!b.mouseOverBanner&&(clearTimeout(b.timeoutID),b.timeoutID=setTimeout(function(){z(1,b,e,g,f,v,m,D,A,w,t)},1E3*e.autoPlay))}))}function A(a,b,c,g){b=c.origImgsDimensions[b].split(";");g.responsive&&
(b[0]/=g.origWidth/g.width,b[1]/=g.origWidth/g.width);a.width(b[0]);a.height(b[1])}function H(a,b,e,g,f,v,m){e.responsive&&(imgInside=c("#contentHolderUnit_"+a,f).find("img:first"),null!=imgInside.width()&&A(imgInside,a,b,e),textIdChildren=c(c(g[a]).attr("data-text-id")).children(),k=-1,textIdChildren.each(function(){k++;imgInside=c(this).find("img:first");null!=imgInside.width()&&A(imgInside,c(g[a]).attr("data-text-id")+"-"+k,b,e)}),c(c(g[a]).attr("data-text-id")).css({width:v.width()+"px",left:parseInt(a*
e.width,10),top:m.css("top")}))}function L(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));return parseInt(a,10)}c.fn.allinone_contentSlider=function(a){a=c.extend({},c.fn.allinone_contentSlider.defaults,a);return this.each(function(){var b=c(this);responsiveWidth=b.parent().width();responsiveHeight=b.parent().height();a.responsiveRelativeToBrowser&&(responsiveWidth=c(window).width(),responsiveHeight=
c(window).height());a.origWidth=a.width;a.width100Proc&&(a.width=responsiveWidth);a.origHeight=a.height;a.height100Proc&&(a.height=responsiveHeight);a.responsive&&(a.origWidth!=responsiveWidth||a.width100Proc)&&(a.width=a.origWidth>responsiveWidth||a.width100Proc?responsiveWidth:a.origWidth,a.height100Proc||(a.height=a.width/(a.origWidth/a.origHeight)));var e=c("<div></div>").addClass("allinone_contentSlider").addClass(a.skin),g=c('<div class="bannerControls">   <div class="leftNav"></div>   <div class="rightNav"></div>    </div>  <div class="contentHolderVisibleWrapper"><div class="contentHolder"></div></div>   <div class="playOver"></div>  <canvas class="mycanvas"></canvas>');
b.wrap(e);b.after(g);var f=b.parent(".allinone_contentSlider"),g=c(".bannerControls",f),v=c(".contentHolderVisibleWrapper",f),m=c(".contentHolder",f),e=c('<div class="bottomNavLeft"></div>'),D=c('<div class="bottomNav"></div>'),G=c('<div class="bottomNavRight"></div>');b.after(e);b.after(D);b.after(G);a.showAllControllers||g.css("display","none");var w=c(".leftNav",f),t=c(".rightNav",f);w.css("display","none");t.css("display","none");a.showNavArrows&&a.showOnInitNavArrows&&(w.css("display","block"),
t.css("display","block"));var l=c(".bottomNav",f),y=c(".bottomNavLeft",f),B=c(".bottomNavRight",f),E;l.css("display","block");y.css("display","block");B.css("display","block");l.css({bottom:a.thumbsWrapperMarginBottom+"px",top:"auto"});y.css({bottom:a.thumbsWrapperMarginBottom+"px",top:"auto"});B.css({bottom:a.thumbsWrapperMarginBottom+"px",top:"auto"});a.showBottomNav||(l.css("display","none"),y.css("display","none"),B.css("display","none"));a.showOnInitBottomNav||(l.css("left","-5000px"),y.css("left",
"-5000px"),B.css("left","-5000px"));a.enableTouchScreen&&f.swipe({swipe:function(c,e,h,l,q){d.effectIsRunning||z("right"==e?-1:1,d,a,p,x,n,b,g,m,f,u)}});var e=L(),u=c(".playOver",f);u.css({left:parseInt((a.width-u.width())/2,10)+"px",top:parseInt((a.height-u.height())/2,10)+"px"});var p=0,d={current_img_no:0,currentImg:0,previous_current_img_no:0,slideIsRunning:!1,mouseOverBanner:!1,isVideoPlaying:!1,timeoutID:"",intervalID:"",arcInitialTime:(new Date).getTime(),timeElapsed:0,windowWidth:0,origImgsDimensions:[],
canvas:"",ctx:"",bannerRatio:a.origWidth/a.origHeight};d.canvas=c(".mycanvas",f)[0];d.canvas.width=2*a.circleRadius+4*a.circleLineWidth;d.canvas.height=2*a.circleRadius+4*a.circleLineWidth;-1!=e&&9>e&&(a.showCircleTimer=!1);a.showCircleTimer&&(d.ctx=d.canvas.getContext("2d"));f.width(a.width);f.height(a.height);v.width(a.width);v.height(a.height);m.width(a.width);m.height(a.height);g.css("margin-top",parseInt((a.height-w.height())/2,10)+"px");var n=b.find("ul:first").children(),C,M=0,r,F=0,N=0,q;
n.each(function(){d.currentImg=c(this);d.currentImg.is("li")||(d.currentImg=d.currentImg.find("li:first"));if(d.currentImg.is("li")){p++;C=c('<div class="contentHolderUnit" rel="'+(p-1)+'" id="contentHolderUnit_'+(p-1)+'">'+d.currentImg.html()+"</div>");C.width(a.width);C.height(a.height);m.append(C);M+=a.width;q=c("#contentHolderUnit_"+(p-1),f).find("img:first");null!=q.width()?(d.origImgsDimensions[p-1]=q.width()+";"+q.height(),a.responsive&&a.origWidth!=responsiveWidth&&A(q,p-1,d,a)):d.origImgsDimensions[p-
1]=null;r=c('<div class="bottomNavButtonOFF" rel="'+(p-1)+'"></div>');l.append(r);F+=parseInt(r.css("padding-left").substring(0,r.css("padding-left").length-2),10)+r.width();N=parseInt((l.height()-parseInt(r.css("height").substring(0,r.css("height").length-2)))/2,10);r.css("margin-top",N+"px");m.append(c(d.currentImg.attr("data-text-id")));c(d.currentImg.attr("data-text-id")).css({width:b.width()+"px",left:parseInt((p-1)*a.width,10),top:g.css("top")});var e=-1;c(d.currentImg.attr("data-text-id")).children().each(function(){e++;
q=c(this).find("img:first");null!=q.width()?(d.origImgsDimensions[d.currentImg.attr("data-text-id")+"-"+e]=q.width()+";"+q.height(),a.responsive&&a.origWidth!=responsiveWidth&&A(q,d.currentImg.attr("data-text-id")+"-"+e,d,a)):d.origImgsDimensions[d.currentImg.attr("data-text-id")+"-"+e]=null})}});m.width(M);l.width(F);a.showOnInitBottomNav&&(l.css("left",parseInt((f.width()-F)/2,10)+"px"),y.css("left",parseInt(l.css("left").substring(0,l.css("left").length-2),10)-y.width()+"px"),B.css("left",parseInt(l.css("left").substring(0,
l.css("left").length-2),10)+l.width()+parseInt(r.css("padding-left").substring(0,r.css("padding-left").length-2),10)+"px"));c("iframe",f).each(function(){var a=c(this).attr("src"),b="?wmode=transparent";-1!=a.indexOf("?")&&(b="&wmode=transparent");c(this).attr("src",a+b)});d.current_img_no=0;d.currentImg=c(n[0]);K(d,a,b,g);f.mouseenter(function(){d.mouseOverBanner=!0;clearTimeout(d.timeoutID);nowx=(new Date).getTime();d.timeElapsed+=nowx-d.arcInitialTime;a.autoHideNavArrows&&a.showNavArrows&&(w.css("display",
"block"),t.css("display","block"));a.autoHideBottomNav&&a.showBottomNav&&(l.css({display:"block",left:parseInt((f.width()-F)/2,10)+"px"}),y.css({display:"block",left:parseInt(l.css("left").substring(0,l.css("left").length-2),10)-y.width()+"px"}),B.css({display:"block",left:parseInt(l.css("left").substring(0,l.css("left").length-2),10)+l.width()+parseInt(r.css("padding-left").substring(0,r.css("padding-left").length-2),10)+"px"}))});f.mouseleave(function(){d.mouseOverBanner=!1;nowx=(new Date).getTime();
a.autoHideNavArrows&&a.showNavArrows&&(w.css("display","none"),t.css("display","none"));a.autoHideBottomNav&&a.showBottomNav&&(l.css("display","none"),y.css("display","none"),B.css("display","none"));if(0<a.autoPlay&&1<p&&!d.isVideoPlaying){clearTimeout(d.timeoutID);d.arcInitialTime=(new Date).getTime();var c=parseInt(1E3*a.autoPlay-(d.timeElapsed+nowx-d.arcInitialTime),10);d.timeoutID=setTimeout(function(){z(1,d,a,p,x,n,b,g,m,f,u)},c)}});C=c(".contentHolderUnit",m);C.click(function(){var b=c(this).attr("rel");
"true"==c(n[d.current_img_no]).attr("data-video")&&(b!=d.current_img_no?d.isVideoPlaying=!1:(clearTimeout(d.timeoutID),q=c(this).find("img:first"),q.css("display","none"),u.css("display","none"),d.isVideoPlaying=!0));void 0!=c(n[d.current_img_no]).attr("data-link")&&b==d.current_img_no&&""!=c(n[d.current_img_no]).attr("data-link")&&(b=a.target,void 0!=c(n[d.current_img_no]).attr("data-target")&&""!=c(n[d.current_img_no]).attr("data-target")&&(b=c(n[d.current_img_no]).attr("data-target")),"_blank"==
b?window.open(c(n[d.current_img_no]).attr("data-link")):window.location=c(n[d.current_img_no]).attr("data-link"))});u.click(function(){u.css("display","none");clearTimeout(d.timeoutID);q=c("#contentHolderUnit_"+d.current_img_no,f).find("img:first");q.css("display","none");d.isVideoPlaying=!0});w.click(function(){d.slideIsRunning||(d.isVideoPlaying=!1,clearTimeout(d.timeoutID),z(-1,d,a,p,x,n,b,g,m,f,u))});t.click(function(){d.slideIsRunning||(d.isVideoPlaying=!1,clearTimeout(d.timeoutID),z(1,d,a,p,
x,n,b,g,m,f,u))});var J=!1;c(window).resize(function(){var e=L();doResizeNow=!0;-1!=navigator.userAgent.indexOf("Android")&&(0==a.windowOrientationScreenSize0&&0==window.orientation&&(a.windowOrientationScreenSize0=c(window).width()),0==a.windowOrientationScreenSize90&&90==window.orientation&&(a.windowOrientationScreenSize90=c(window).height()),0==a.windowOrientationScreenSize_90&&-90==window.orientation&&(a.windowOrientationScreenSize_90=c(window).height()),a.windowOrientationScreenSize0&&0==window.orientation&&
c(window).width()>a.windowOrientationScreenSize0&&(doResizeNow=!1),a.windowOrientationScreenSize90&&90==window.orientation&&c(window).height()>a.windowOrientationScreenSize90&&(doResizeNow=!1),a.windowOrientationScreenSize_90&&-90==window.orientation&&c(window).height()>a.windowOrientationScreenSize_90&&(doResizeNow=!1),0==d.windowWidth&&(doResizeNow=!1,d.windowWidth=c(window).width()));-1!=e&&9==e&&0==d.windowWidth&&(doResizeNow=!1);d.windowWidth==c(window).width()?(doResizeNow=!1,a.windowCurOrientation!=
window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,doResizeNow=!0)):d.windowWidth=c(window).width();a.responsive&&doResizeNow&&(!1!==J&&clearTimeout(J),J=setTimeout(function(){var e=d,h=a,I=p,q=n,r=g,t=u,y=x;responsiveWidth=b.parent().parent().width();responsiveHeight=b.parent().parent().height();h.responsiveRelativeToBrowser&&(responsiveWidth=c(window).width(),responsiveHeight=c(window).height());h.width100Proc&&(h.width=responsiveWidth);h.height100Proc&&
(h.height=responsiveHeight);if(h.origWidth!=responsiveWidth||h.width100Proc){h.origWidth>responsiveWidth||h.width100Proc?h.width=responsiveWidth:h.width100Proc||(h.width=h.origWidth);h.height100Proc||(h.height=h.width/e.bannerRatio);f.width(h.width);f.height(h.height);v.width(h.width);v.height(h.height);m.width(h.width);m.height(h.height);r.css("margin-top",parseInt((h.height-w.height())/2,10)+"px");contentHolderUnit=c(".contentHolderUnit",f);contentHolderUnit.width(h.width);contentHolderUnit.height(h.height);
holderWidth=h.width*I;for(i=0;i<I;i++)H(i,e,h,q,f,b,r);m.width(holderWidth);l.css({left:parseInt((f.width()-l.width())/2,10)+"px"});t.css({left:parseInt((h.width-t.width())/2,10)+"px",top:parseInt((h.height-t.height())/2,10)+"px"});clearTimeout(e.timeoutID);z(1,e,h,I,y,q,b,r,m,f,t)}},300))});var x=c(".bottomNavButtonOFF",f);x.click(function(){if(!d.slideIsRunning){d.isVideoPlaying=!1;var e=c(this).attr("rel");c(x[d.current_img_no]).removeClass("bottomNavButtonON");d.previous_current_img_no=d.current_img_no;
c("#contentHolderUnit_"+d.previous_current_img_no,f).html(c(n[d.previous_current_img_no]).html());H(d.previous_current_img_no,d,a,n,f,b,g);d.current_img_no=e-1;z(1,d,a,p,x,n,b,g,m,f,u)}});x.mouseenter(function(){var b=c(this),d=b.attr("rel");a.showPreviewThumbs&&(E=c('<div class="bottomOverThumb"></div>'),b.append(E),d=c(n[d]).attr("data-bottom-thumb"),E.html('<img src="'+d+'">'));b.addClass("bottomNavButtonON")});x.mouseleave(function(){var b=c(this),e=b.attr("rel");a.showPreviewThumbs&&E.remove();
d.current_img_no!=e&&b.removeClass("bottomNavButtonON")});c(x[d.current_img_no]).addClass("bottomNavButtonON");0<a.autoPlay&&1<p&&(a.showCircleTimer&&(d.intervalID=setInterval(function(){var b=d,c=a;nowx=(new Date).getTime();b.mouseOverBanner||b.effectIsRunning||!c.showCircleTimer||(b.ctx.clearRect(0,0,b.canvas.width,b.canvas.height),b.ctx.beginPath(),b.ctx.globalAlpha=c.behindCircleAlpha/100,b.ctx.arc(c.circleRadius+2*c.circleLineWidth,c.circleRadius+2*c.circleLineWidth,c.circleRadius,0,2*Math.PI,
!1),b.ctx.lineWidth=c.circleLineWidth+2,b.ctx.strokeStyle=c.behindCircleColor,b.ctx.stroke(),b.ctx.beginPath(),b.ctx.globalAlpha=c.circleAlpha/100,b.ctx.arc(c.circleRadius+2*c.circleLineWidth,c.circleRadius+2*c.circleLineWidth,c.circleRadius,0,(b.timeElapsed+nowx-b.arcInitialTime)/1E3*2/c.autoPlay*Math.PI,!1),b.ctx.lineWidth=c.circleLineWidth,b.ctx.strokeStyle=c.circleColor,b.ctx.stroke())},125)),d.timeoutID=setTimeout(function(){z(1,d,a,p,x,n,b,g,m,f,u)},1E3*a.autoPlay));"true"==c(n[d.current_img_no]).attr("data-video")&&
u.css("display","block")})};c.fn.allinone_contentSlider.defaults={skin:"imposing",width:918,height:382,width100Proc:!1,height100Proc:!1,autoPlay:7,loop:!0,target:"_blank",absUrl:"",showAllControllers:!0,showNavArrows:!0,showOnInitNavArrows:!0,autoHideNavArrows:!0,showBottomNav:!0,showOnInitBottomNav:!0,autoHideBottomNav:!0,showPreviewThumbs:!0,enableTouchScreen:!0,showCircleTimer:!0,showCircleTimerIE8IE7:!1,circleRadius:10,circleLineWidth:4,circleColor:"#FF0000",circleAlpha:100,behindCircleColor:"#000000",
behindCircleAlpha:50,responsive:!1,responsiveRelativeToBrowser:!0,thumbsWrapperMarginBottom:-35,origWidth:0,origHeight:0,origThumbW:0,origThumbH:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);