/*
 * AllInOne Banner - Banner With Playlist v3.5
 *
 * Copyright 2012-2017, LambertGroup
 *
*/


(function(f){function M(a,c,b){b.responsive&&(newCss="",-1!=a.css("font-size").lastIndexOf("px")?(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("px")),newCss+="font-size:"+fontSize/(b.origWidth/b.width)+"px;"):-1!=a.css("font-size").lastIndexOf("em")&&(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("em")),newCss+="font-size:"+fontSize/(b.origWidth/b.width)+"em;"),-1!=a.css("line-height").lastIndexOf("px")?(lineHeight=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("px")),
newCss+="line-height:"+lineHeight/(b.origWidth/b.width)+"px;"):-1!=a.css("line-height").lastIndexOf("em")&&(lineHeight=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("em")),newCss+="line-height:"+lineHeight/(b.origWidth/b.width)+"em;"),a.wrapInner('<div class="newFS" style="'+newCss+'" />'));var k=a.attr("data-final-left"),g=a.attr("data-final-top");b.responsive&&(k=parseInt(k/(b.origWidth/b.width),10),g=parseInt(g/(b.origWidth/b.width),10));b=1;1==c.isVideoPlaying&&(b=0);a.animate({opacity:b,
left:k+"px",top:g+"px"},1E3*a.attr("data-duration"),function(){1==c.isVideoPlaying&&f(c.currentImg.attr("data-text-id")).children().css("opacity",0)})}function I(a,c,b,k){f(a.currentImg.attr("data-text-id")).css("display","block");b=f(a.currentImg.attr("data-text-id")).children();var g=0;currentText_arr=[];b.each(function(){currentText_arr[g]=f(this);var d=currentText_arr[g].attr("data-initial-left"),b=currentText_arr[g].attr("data-initial-top");c.responsive&&(d=parseInt(d/(c.origWidth/c.width),10),
b=parseInt(b/(c.origWidth/c.width),10));currentText_arr[g].css({left:d+"px",top:b+"px",opacity:parseInt(currentText_arr[g].attr("data-fade-start"),10)/100});var k=currentText_arr[g];setTimeout(function(){M(k,a,c)},1E3*currentText_arr[g].attr("data-delay"));g++})}function N(a){for(var c,b,f=a.length;f;c=parseInt(Math.random()*f,10),b=a[--f],a[f]=a[c],a[c]=b);return a}function J(a,c){nowx=(new Date).getTime();a.mouseOverBanner||a.effectIsRunning||!c.showCircleTimer||(a.ctx.clearRect(0,0,a.canvas.width,
a.canvas.height),a.ctx.beginPath(),a.ctx.globalAlpha=c.behindCircleAlpha/100,a.ctx.arc(c.circleRadius+2*c.circleLineWidth,c.circleRadius+2*c.circleLineWidth,c.circleRadius,0,2*Math.PI,!1),a.ctx.lineWidth=c.circleLineWidth+2,a.ctx.strokeStyle=c.behindCircleColor,a.ctx.stroke(),a.ctx.beginPath(),a.ctx.globalAlpha=c.circleAlpha/100,a.ctx.arc(c.circleRadius+2*c.circleLineWidth,c.circleRadius+2*c.circleLineWidth,c.circleRadius,0,(a.timeElapsed+nowx-a.arcInitialTime)/1E3*2/c.autoPlay*Math.PI,!1),a.ctx.lineWidth=
c.circleLineWidth,a.ctx.strokeStyle=c.circleColor,a.ctx.stroke())}function K(a,c,b){var k=F();f(".stripe",a).remove();f(".block",a).remove();B=w=Math.round(a.width()/c.numberOfStripes);for(var g=!0,d=0;d<c.numberOfStripes;d++)d==c.numberOfStripes-1&&(B=a.width()-w*(c.numberOfStripes-1)),!c.responsive||-1==k||-1!=k&&9<=k?-1!=p.indexOf("ipad")||-1!=p.indexOf("iphone")||-1!=p.indexOf("ipod")||-1!=p.indexOf("webos")?g=!1:a.append(f('<div class="stripe"></div>').css({opacity:"0",left:w*d+"px",width:B+
"px",height:"0px",background:'url("'+b.current_imgInside.attr("src")+'") '+-1*d*w+"px 0%"})):g=!1,g||(mleft=-1*w*d,a.append(f('<div class="stripe"><img src="'+b.current_imgInside.attr("src")+'" width="'+a.width()+'" height="'+a.height()+'" style="margin-left:'+mleft+'px;"></div>').css({opacity:"0",left:w*d+"px",width:B+"px",height:"0px"})));c.responsive&&g&&(-1==k||-1!=k&&9<=k)&&f(".stripe",a).css({"-webkit-background-size":a.width()+"px "+a.height()+"px","-moz-background-size":a.width()+"px "+a.height()+
"px","-o-background-size":a.width()+"px "+a.height()+"px","-ms-background-size":a.width()+"px "+a.height()+"px","background-size":a.width()+"px "+a.height()+"px"})}function O(a,c,b){var k=F();f(".stripe",a).remove();f(".block",a).remove();for(var g=Math.round(a.width()/c.numberOfColumns),d=Math.round(a.height()/c.numberOfRows),G,n,u,r,t=!0,m=0;m<c.numberOfRows;m++)for(var h=0;h<c.numberOfColumns;h++)u=g*h,r=d*m,G=h==c.numberOfColumns-1?a.width()-g*(c.numberOfColumns-1):g,n=m==c.numberOfRows-1?a.height()-
d*(c.numberOfRows-1):d,!c.responsive||-1==k||-1!=k&&9<=k?-1!=p.indexOf("ipad")||-1!=p.indexOf("iphone")||-1!=p.indexOf("ipod")||-1!=p.indexOf("webos")?t=!1:a.append(f('<div class="block"></div>').css({opacity:"0",left:u+"px",top:r+"px",width:G+"px",height:n+"px",background:'url("'+b.current_imgInside.attr("src")+'") -'+u+"px -"+r+"px"})):t=!1,t||(mleft=-1*u,mtop=-1*r,a.append(f('<div class="block"><img src="'+b.current_imgInside.attr("src")+'" width="'+a.width()+'" height="'+a.height()+'" style="margin-left:'+
mleft+"px; margin-top:"+mtop+'px;"></div>').css({opacity:"0",left:u+"px",top:r+"px",width:G+"px",height:n+"px"})));c.responsive&&t&&(-1==k||-1!=k&&9<=k)&&f(".block",a).css({"-webkit-background-size":a.width()+"px "+a.height()+"px","-moz-background-size":a.width()+"px "+a.height()+"px","-o-background-size":a.width()+"px "+a.height()+"px","-ms-background-size":a.width()+"px "+a.height()+"px","background-size":a.width()+"px "+a.height()+"px"})}function H(a,c,b,f,g){var d=a.width(),k=a.height();a.css({width:"0"});
a.css({height:"0"});c==f.numberOfRows-1&&b==f.numberOfColumns-1?setTimeout(function(){a.animate({opacity:"1.0",width:d,height:k},1E3*f.effectDuration/3,"",function(){g.trigger("effectComplete")})},n):setTimeout(function(){a.animate({opacity:"1.0",width:d,height:k},1E3*f.effectDuration/3)},n);n+=25}function D(a,c,b,k,g,d,p,D,u,r){var t=!0;if(!b.loop&&c.current_img_no+a>=k||!b.loop&&0>c.current_img_no+a)t=!1;if(t){f(".newFS",d).contents().unwrap();c.arcInitialTime=(new Date).getTime();c.timeElapsed=
0;b.showCircleTimer&&(c.ctx.clearRect(0,0,c.canvas.width,c.canvas.height),c.ctx.beginPath(),c.ctx.globalAlpha=b.behindCircleAlpha/100,c.ctx.arc(b.circleRadius+2*b.circleLineWidth,b.circleRadius+2*b.circleLineWidth,b.circleRadius,0,2*Math.PI,!1),c.ctx.lineWidth=b.circleLineWidth+2,c.ctx.strokeStyle=b.behindCircleColor,c.ctx.stroke(),c.ctx.beginPath(),c.ctx.globalAlpha=b.circleAlpha/100,c.ctx.arc(b.circleRadius+2*b.circleLineWidth,b.circleRadius+2*b.circleLineWidth,b.circleRadius,0,0,!1),c.ctx.lineWidth=
b.circleLineWidth,c.ctx.strokeStyle=b.circleColor,c.ctx.stroke());f(c.currentImg.attr("data-text-id")).css("display","none");f(g[c.current_img_no]).removeClass("thumbsHolder_ThumbON");b.randomizeImages&&!c.bottomNavClicked?(t=Math.floor(Math.random()*k),c.current_img_no=c.current_img_no===t?Math.floor(Math.random()*k):t):c.current_img_no=c.current_img_no+a>=k?0:0>c.current_img_no+a?k-1:c.current_img_no+a;c.bottomNavClicked=!1;f(g[c.current_img_no]).addClass("thumbsHolder_ThumbON");E(0,p,k,D,b,c,u);
c.currentImg=f(r[c.current_img_no]);c.current_imgInside=c.currentImg.find("img:first");c.currentImg.attr("data-transition")?(current_effect=c.currentImg.attr("data-transition"),"random"==current_effect&&(current_effect=x[Math.floor(Math.random()*x.length)])):current_effect="random"!=b.defaultEffect?b.defaultEffect:x[Math.floor(Math.random()*x.length)];"alternateSlide"==current_effect&&(current_effect=1===a?"slideFromRight":"slideFromLeft");c.effectIsRunning=!0;if("fade"==current_effect||"slideFromLeft"==
current_effect||"slideFromRight"==current_effect||"slideFromTop"==current_effect||"slideFromBottom"==current_effect)K(d,b,c),a=f(".stripe:first",d),"fade"==current_effect&&(a.css({top:"0px",height:"100%",width:d.width()+"px"}),a.animate({opacity:"1.0"},2E3*b.effectDuration,"",function(){d.trigger("effectComplete")})),"slideFromLeft"==current_effect&&(a.css({top:"0px",height:"100%",width:"0"}),a.animate({opacity:"1.0",width:d.width()+"px"},1E3*b.effectDuration,"",function(){d.trigger("effectComplete")})),
"slideFromRight"==current_effect&&(a.css({top:"0px",height:"100%",width:"0",left:d.width()+5+"px"}),a.animate({opacity:"1.0",left:"0",width:d.width()+"px"},1E3*b.effectDuration,"",function(){d.trigger("effectComplete")})),"slideFromTop"==current_effect&&(a.css({top:"0px",height:"0",width:d.width()+"px"}),a.animate({opacity:"1.0",height:d.height()+"px"},1E3*b.effectDuration,"",function(){d.trigger("effectComplete")})),"slideFromBottom"==current_effect&&(a.css({height:"0",width:d.width()+"px",top:d.height()+
"px"}),a.animate({opacity:"1.0",top:0,height:d.height()+"px"},1E3*b.effectDuration,"",function(){d.trigger("effectComplete")}));0<=current_effect.indexOf("Stripes")&&(K(d,b,c),a=0<=current_effect.indexOf("Reverse")?f(".stripe",d).myReverse():f(".stripe",d),n=100,i=0,a.each(function(){var a=f(this);"topBottomDroppingStripes"!=current_effect&&"topBottomDroppingReverseStripes"!=current_effect||a.css({top:"0px"});"bottomTopDroppingStripes"!=current_effect&&"bottomTopDroppingReverseStripes"!=current_effect||
a.css({bottom:"0px"});"leftRightFadingStripes"!=current_effect&&"leftRightFadingReverseStripes"!=current_effect||a.css({top:"0px",height:"100%",width:"0"});"asynchronousDroppingStripes"==current_effect&&(i%2?a.css({top:"0px"}):a.css({bottom:"0px"}));if("leftRightFadingStripes"==current_effect||"leftRightFadingReverseStripes"==current_effect){var c=w;if("leftRightFadingStripes"==current_effect&&i==b.numberOfStripes-1||"leftRightFadingReverseStripes"==current_effect&&0==i)c=B;i==b.numberOfStripes-1?
setTimeout(function(){a.animate({width:c+"px",opacity:"1.0"},800*b.effectDuration,"",function(){d.trigger("effectComplete")})},n):setTimeout(function(){a.animate({width:c+"px",opacity:"1.0"},800*b.effectDuration)},n)}else i==b.numberOfStripes-1?setTimeout(function(){a.animate({height:"100%",opacity:"1.0"},1E3*b.effectDuration,"",function(){d.trigger("effectComplete")})},n):setTimeout(function(){a.animate({height:"100%",opacity:"1.0"},1E3*b.effectDuration)},n);n+=50;i++}));if(0<=current_effect.indexOf("Blocks"))if(O(d,
b,c),c=0<=current_effect.indexOf("Reverse")?f(".block",d).myReverse():"randomBlocks"==current_effect?N(f(".block",d)):f(".block",d),n=100,"randomBlocks"==current_effect){i=0;var m=b.numberOfRows*b.numberOfColumns;c.each(function(){var a=f(this),c=a.width(),e=a.height();a.css({width:"0",height:"0"});i==m-1?setTimeout(function(){a.animate({opacity:"1.0",width:c,height:e},1E3*b.effectDuration/3,"",function(){d.trigger("effectComplete")})},n):setTimeout(function(){a.animate({opacity:"1.0",width:c,height:e},
1E3*b.effectDuration/3)},n);n+=25;i++})}else{var h=0,l=0,e=[];e[h]=[];c.each(function(){e[h][l]=f(this);l++;l==b.numberOfColumns&&(h++,l=0,e[h]=[])});l=h=0;n=100;c=f(e[h][l]);for(H(c,0,0,b,d);h<b.numberOfRows-1||l<b.numberOfColumns-1;)for(h<b.numberOfRows-1&&h++,l<b.numberOfColumns-1&&l++,i=h,l<h&&b.numberOfRows>b.numberOfColumns&&(i=h-l),j=0,h<l&&b.numberOfRows<b.numberOfColumns&&(j=l-h);0<=i&&j<=l;)c=f(e[i--][j++]),H(c,i,j,b,d);n=b.numberOfRows<b.numberOfColumns?n-25*(b.numberOfRows-1):n-25*(b.numberOfColumns-
1);limit_i=0;for(limit_j=l-h;limit_i<h&&limit_j<l;){i=h+1;for(j=limit_j;i>limit_i&&j<l;)--i,j+=1,c=f(e[i][j]),H(c,i,j,b,d);limit_i++;limit_j++}}}}function E(a,c,b,f,g,d,p){b>g.numberOfThumbsPerScreen&&(b=(c.height()+d.thumbMarginTop)*(b-g.numberOfThumbsPerScreen),f.stop(!0,!0),a&&!d.isCarouselScrolling?(d.isCarouselScrolling=!0,1>=a&&(a=0),f.animate({top:parseInt(g.borderWidth/(g.origWidth/g.width)+b*(a-100)/100,10)+"px"},1100,"easeOutQuad",function(){d.isCarouselScrolling=!1})):d.isCarouselScrolling||
(d.isCarouselScrolling=!0,f.css("opacity","0.5"),a=parseInt(g.borderWidth/(g.origWidth/g.width)-(c.height()+d.thumbMarginTop)*d.current_img_no,10),Math.abs(a)>b&&(a=g.borderWidth/(g.origWidth/g.width)-b),p.slider("value",100+parseInt(100*a/b,10)),f.animate({opacity:1,top:a+"px"},500,"easeOutCubic",function(){d.isCarouselScrolling=!1})))}function L(a,c,b,k,g,d,p,n,u,r,t,m){g.css({height:parseInt(c.origThumbH/(c.origWidth/c.width),10)+"px"});r.css({"padding-left":parseInt(c.origthumbLeftPadding/(c.origWidth/
c.width),10)+"px","padding-right":parseInt(c.origthumbRightPadding/(c.origWidth/c.width),10)+"px","padding-top":parseInt(c.origthumbTopPadding/(c.origWidth/c.width),10)+"px","padding-bottom":parseInt(c.origthumbBottomPadding/(c.origWidth/c.width),10)+"px"});b="px";-1!=t.css("font-size").lastIndexOf("em")&&(b="em");g="px";-1!=t.css("line-height").lastIndexOf("em")&&(g="em");t.css({"font-size":parseInt(c.origthumbTitleFont/(c.origWidth/c.width),10)+b,"line-height":parseInt(c.origthumbTitleLineHeight/
(c.origWidth/c.width),10)+g});b="px";-1!=m.css("font-size").lastIndexOf("em")&&(b="em");g="px";-1!=m.css("line-height").lastIndexOf("em")&&(g="em");m.css({"font-size":parseInt(c.origthumbRegFont/(c.origWidth/c.width),10)+b,"line-height":parseInt(c.origthumbRegLineHeight/(c.origWidth/c.width),10)+g});c.showThumbs&&f(".thumbsHolder_ThumbOFF",k).find("img:first").css({width:parseInt(c.origThumbImgW/(c.origWidth/c.width),10)+"px",height:parseInt(c.origThumbImgH/(c.origWidth/c.width),10)+"px"});a.thumbMarginTop=
Math.floor((u.height()-p.height()*c.numberOfThumbsPerScreen)/(c.numberOfThumbsPerScreen-1));thumb_i=0;d.children().each(function(){thumb_i++;theThumb=f(this);1>=thumb_i?theThumb.css("margin-top",Math.floor((u.height()-2*c.borderWidth/(c.origWidth/c.width)-(a.thumbMarginTop+theThumb.height())*(c.numberOfThumbsPerScreen-1)-theThumb.height())/2)+"px"):theThumb.css("margin-top",a.thumbMarginTop+"px")})}function F(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&
(a=parseFloat(RegExp.$1));return parseInt(a,10)}var x="fade slideFromLeft slideFromRight slideFromTop slideFromBottom topBottomDroppingStripes topBottomDroppingReverseStripes bottomTopDroppingStripes bottomTopDroppingReverseStripes asynchronousDroppingStripes leftRightFadingStripes leftRightFadingReverseStripes topBottomDiagonalBlocks topBottomDiagonalReverseBlocks alternateSlide randomBlocks".split(" "),w,B,n=100,p=navigator.userAgent.toLowerCase();f.fn.allinone_bannerWithPlaylist=function(a){a=
f.extend({},f.fn.allinone_bannerWithPlaylist.defaults,a);return this.each(function(){var c=f(this);responsiveWidth=c.parent().width();responsiveHeight=c.parent().height();a.responsiveRelativeToBrowser&&(responsiveWidth=f(window).width(),responsiveHeight=f(window).height());a.origWidth=a.width;a.width100Proc&&(a.width=responsiveWidth);a.origHeight=a.height;a.height100Proc&&(a.height=responsiveHeight);a.responsive&&(a.origWidth!=responsiveWidth||a.width100Proc)&&(a.width=a.origWidth>responsiveWidth||
a.width100Proc?responsiveWidth:a.origWidth,a.height100Proc||(a.height=a.width/(a.origWidth/a.origHeight)));a.width=parseInt(a.width,10);a.height=parseInt(a.height,10);c.css("display","block");var b=f("<div></div>").addClass("allinone_bannerWithPlaylistBorder"),k=f("<div></div>").addClass("allinone_bannerWithPlaylist").addClass(a.skin),g=f('<div class="bannerControls">   <div class="leftNav"></div>   <div class="rightNav"></div>    <div class="thumbsHolderWrapper"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div>  <div class="slider-vertical"></div>     </div>  <canvas class="mycanvas"></canvas>');
c.wrap(k);c.after(g);a.showAllControllers||g.css("display","none");var d=c.parent(".allinone_bannerWithPlaylist"),g=f(".bannerControls",d);d.wrap(b);var n=d.parent(".allinone_bannerWithPlaylistBorder"),w=f(".leftNav",d),u=f(".rightNav",d);w.css("display","none");u.css("display","none");a.showNavArrows&&a.showOnInitNavArrows&&(w.css("display","block"),u.css("display","block"));var r=f(".thumbsHolderWrapper",d),t=f(".thumbsHolderVisibleWrapper",d),m=f(".thumbsHolder",d),h=f(".slider-vertical",d),b=
F(),l=0,e={current_img_no:0,currentImg:0,current_imgInside:"",windowWidth:0,carouselStep:0,thumbMarginTop:0,bottomNavClicked:!1,effectIsRunning:!1,mouseOverBanner:!1,timeoutID:"",intervalID:"",arcInitialTime:(new Date).getTime(),timeElapsed:0,canvas:"",ctx:"",bannerRatio:a.origWidth/a.origHeight};e.canvas=f(".mycanvas",d)[0];e.canvas.width=2*a.circleRadius+4*a.circleLineWidth;e.canvas.height=2*a.circleRadius+4*a.circleLineWidth;-1!=b&&9>b&&(a.showCircleTimer=!1);a.showCircleTimer&&(e.ctx=e.canvas.getContext("2d"));
n.width(a.width);n.height(a.height);n.css("background",a.borderColor);d.width(a.width-3*a.borderWidth/(a.origWidth/a.width)-a.playlistWidth/(a.origWidth/a.width));d.height(a.height-2*a.borderWidth/(a.origWidth/a.width));d.css({left:a.borderWidth/(a.origWidth/a.width)+"px",top:a.borderWidth/(a.origWidth/a.width)+"px"});g.width("100%");g.height("100%");t.width(a.playlistWidth/(a.origWidth/a.width));t.height(d.height());r.width(a.playlistWidth/(a.origWidth/a.width));r.height(d.height());r.css({top:0,
right:-1*(a.borderWidth/(a.origWidth/a.width)+a.playlistWidth/(a.origWidth/a.width))+"px"});m.width(a.playlistWidth/(a.origWidth/a.width));m.css("top",a.borderWidth/(a.origWidth/a.width)+"px");var v=c.find("ul:first").children(),q,B="",k=0;v.each(function(){e.currentImg=f(this);e.currentImg.is("li")||(e.currentImg=e.currentImg.find("li:first"));if(e.currentImg.is("li")){e.currentImg.css("display","none");l++;var c=f(v[l-1]).attr("data-bottom-thumb");B="";a.showThumbs&&(B='<img src="'+c+'">');q=f('<div class="thumbsHolder_ThumbOFF" rel="'+
(l-1)+'"><div class="padding">'+B+'<span class="title">'+e.currentImg.attr("data-title")+'</span><span class="reg">'+e.currentImg.attr("data-desc")+"</span></div></div>");m.append(q);0==a.origThumbW&&(0==a.numberOfThumbsPerScreen&&(a.numberOfThumbsPerScreen=Math.floor(a.origHeight/q.height())),a.origThumbW=q.width(),a.origThumbH=q.height(),C=f(".thumbsHolder_ThumbOFF .padding",d),a.origthumbLeftPadding=C.css("padding-left").substr(0,C.css("padding-left").lastIndexOf("px")),a.origthumbRightPadding=
C.css("padding-right").substr(0,C.css("padding-left").lastIndexOf("px")),a.origthumbTopPadding=C.css("padding-top").substr(0,C.css("padding-left").lastIndexOf("px")),a.origthumbBottomPadding=C.css("padding-bottom").substr(0,C.css("padding-left").lastIndexOf("px")),e.thumbMarginTop=Math.floor((r.height()-q.height()*a.numberOfThumbsPerScreen)/(a.numberOfThumbsPerScreen-1)),y=f(".thumbsHolder_ThumbOFF .title",d),z=f(".thumbsHolder_ThumbOFF .reg",d),-1!=y.css("font-size").lastIndexOf("px")?a.origthumbTitleFont=
y.css("font-size").substr(0,y.css("font-size").lastIndexOf("px")):-1!=y.css("font-size").lastIndexOf("em")&&(a.origthumbTitleFont=y.css("font-size").substr(0,y.css("font-size").lastIndexOf("em"))),-1!=y.css("line-height").lastIndexOf("px")?a.origthumbTitleLineHeight=y.css("line-height").substr(0,y.css("line-height").lastIndexOf("px")):-1!=y.css("line-height").lastIndexOf("em")&&(a.origthumbTitleLineHeight=y.css("line-height").substr(0,y.css("line-height").lastIndexOf("em"))),-1!=z.css("font-size").lastIndexOf("px")?
a.origthumbRegFont=z.css("font-size").substr(0,z.css("font-size").lastIndexOf("px")):-1!=z.css("font-size").lastIndexOf("em")&&(a.origthumbRegFont=z.css("font-size").substr(0,z.css("font-size").lastIndexOf("em"))),-1!=z.css("line-height").lastIndexOf("px")?a.origthumbRegLineHeight=z.css("line-height").substr(0,z.css("line-height").lastIndexOf("px")):-1!=z.css("line-height").lastIndexOf("em")&&(a.origthumbRegLineHeight=z.css("line-height").substr(0,z.css("line-height").lastIndexOf("em"))));m.css("height",
m.height()+e.thumbMarginTop+q.height()+"px");1>=l?q.css("margin-top",Math.floor((r.height()-2*a.borderWidth/(a.origWidth/a.width)-(e.thumbMarginTop+q.height())*(a.numberOfThumbsPerScreen-1)-q.height())/2)+"px"):q.css("margin-top",e.thumbMarginTop+"px")}});var C=f(".thumbsHolder_ThumbOFF .padding",d);var y=f(".thumbsHolder_ThumbOFF .title",d);var z=f(".thumbsHolder_ThumbOFF .reg",d);var A=f(".thumbsHolder_ThumbOFF",d);L(e,a,l,d,A,m,q,t,r,C,y,z);l>a.numberOfThumbsPerScreen&&(h.slider({orientation:"vertical",
range:"min",min:1,max:100,step:1,value:100,slide:function(c,d){E(d.value,q,l,m,a,e,h)}}),0>=a.borderWidth&&(k=h.width()/2),h.height(r.height()-25),h.css({display:"block",left:Math.floor(a.width-2*a.borderWidth/(a.origWidth/a.width)+(a.borderWidth/(a.origWidth/a.width)-h.width())/2)-k+"px"}));e.current_img_no=a.firstImg;a.firstImg>l&&(e.current_img_no=l);0>a.firstImg&&(e.current_img_no=0);a.randomizeImages&&(e.current_img_no=Math.floor(Math.random()*l));e.current_img_no>=a.numberOfThumbsPerScreen&&
E(0,q,l,m,a,e,h);e.currentImg=f(v[e.current_img_no]);e.current_imgInside=e.currentImg.find("img:first");-1!=p.indexOf("ipad")||-1!=p.indexOf("iphone")||-1!=p.indexOf("ipod")||-1!=p.indexOf("webos")||-1!=b&&7>=b?d.append('<img id="curBgImgIos" src="'+e.current_imgInside.attr("src")+'" width="'+d.width()+'" height="'+d.height()+'">'):(d.css("background",'url("'+e.current_imgInside.attr("src")+'") no-repeat'),a.responsive&&(-1==b||-1!=b&&9<=b?d.css({"-webkit-background-size":d.width()+"px "+d.height()+
"px","-moz-background-size":d.width()+"px "+d.height()+"px","-o-background-size":d.width()+"px "+d.height()+"px","-ms-background-size":d.width()+"px "+d.height()+"px","background-size":d.width()+"px "+d.height()+"px"}):8==b&&d.css({filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+e.current_imgInside.attr("src")+"',sizingMethod='scale')"})));a.enableTouchScreen&&d.swipe({swipe:function(c,b,f,g,k){e.effectIsRunning||D("right"==b?-1:1,e,a,l,A,d,q,m,h,v)}});I(e,a,c,g);d.bind("effectComplete",
function(){var b=F();e.effectIsRunning=!1;-1!=p.indexOf("ipad")||-1!=p.indexOf("iphone")||-1!=p.indexOf("ipod")||-1!=p.indexOf("webos")||-1!=b&&7>=b?(f("#curBgImgIos",d).attr("src",e.current_imgInside.attr("src")),f("#curBgImgIos",d).width(d.width()),f("#curBgImgIos",d).height(d.height())):(d.css("background",'url("'+e.current_imgInside.attr("src")+'") no-repeat'),a.responsive&&(-1==b||-1!=b&&9<=b?d.css({"-webkit-background-size":d.width()+"px "+d.height()+"px","-moz-background-size":d.width()+"px "+
d.height()+"px","-o-background-size":d.width()+"px "+d.height()+"px","-ms-background-size":d.width()+"px "+d.height()+"px","background-size":d.width()+"px "+d.height()+"px"}):8==b&&d.css({filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+e.current_imgInside.attr("src")+"',sizingMethod='scale')"})));e.arcInitialTime=(new Date).getTime();e.timeElapsed=0;a.showCircleTimer&&(clearInterval(e.intervalID),e.ctx.clearRect(0,0,e.canvas.width,e.canvas.height),e.ctx.beginPath(),e.ctx.globalAlpha=
a.behindCircleAlpha/100,e.ctx.arc(a.circleRadius+2*a.circleLineWidth,a.circleRadius+2*a.circleLineWidth,a.circleRadius,0,2*Math.PI,!1),e.ctx.lineWidth=a.circleLineWidth+2,e.ctx.strokeStyle=a.behindCircleColor,e.ctx.stroke(),e.ctx.beginPath(),e.ctx.globalAlpha=a.circleAlpha/100,e.ctx.arc(a.circleRadius+2*a.circleLineWidth,a.circleRadius+2*a.circleLineWidth,a.circleRadius,0,0,!1),e.ctx.lineWidth=a.circleLineWidth,e.ctx.strokeStyle=a.circleColor,e.ctx.stroke(),e.intervalID=setInterval(function(){J(e,
a)},125));I(e,a,c,g);0<a.autoPlay&&1<l&&!e.mouseOverBanner&&(clearTimeout(e.timeoutID),e.timeoutID=setTimeout(function(){D(1,e,a,l,A,d,q,m,h,v)},1E3*a.autoPlay))});d.mouseenter(function(){e.mouseOverBanner=!0;clearTimeout(e.timeoutID);nowx=(new Date).getTime();e.timeElapsed+=nowx-e.arcInitialTime;a.autoHideNavArrows&&a.showNavArrows&&(w.css("display","block"),u.css("display","block"))});d.mouseleave(function(){e.mouseOverBanner=!1;nowx=(new Date).getTime();a.autoHideNavArrows&&a.showNavArrows&&(w.css("display",
"none"),u.css("display","none"));if(0<a.autoPlay&&1<l){clearTimeout(e.timeoutID);e.arcInitialTime=(new Date).getTime();var c=parseInt(1E3*a.autoPlay-(e.timeElapsed+nowx-e.arcInitialTime),10);e.timeoutID=setTimeout(function(){D(1,e,a,l,A,d,q,m,h,v)},c)}});d.click(function(){if(void 0!=f(v[e.current_img_no]).attr("data-link")&&""!=f(v[e.current_img_no]).attr("data-link")&&!e.effectIsRunning){var c=a.target;void 0!=f(v[e.current_img_no]).attr("data-target")&&""!=f(v[e.current_img_no]).attr("data-target")&&
(c=f(v[e.current_img_no]).attr("data-target"));"_blank"==c?window.open(f(v[e.current_img_no]).attr("data-link")):window.location=f(v[e.current_img_no]).attr("data-link")}});w.click(function(){e.effectIsRunning||(clearTimeout(e.timeoutID),D(-1,e,a,l,A,d,q,m,h,v))});u.click(function(){e.effectIsRunning||(clearTimeout(e.timeoutID),D(1,e,a,l,A,d,q,m,h,v))});A.click(function(){if(!e.effectIsRunning){var c=f(this).attr("rel");f(A[e.current_img_no]).removeClass("thumbsHolder_ThumbON");e.bottomNavClicked=
!0;e.current_img_no=c-1;D(1,e,a,l,A,d,q,m,h,v)}});A.mouseenter(function(){var a=f(this);a.attr("rel");a.addClass("thumbsHolder_ThumbON")});A.mouseleave(function(){var a=f(this),c=a.attr("rel");e.current_img_no!=c&&a.removeClass("thumbsHolder_ThumbON")});t.mousewheel(function(c,d,b,f){c.preventDefault();c=h.slider("value");if(1<parseInt(c,10)&&-1==parseInt(d,10)||100>parseInt(c,10)&&1==parseInt(d,10))c+=d,h.slider("value",c),E(c,q,l,m,a,e,h)});var x=!1;f(window).resize(function(){var b=F();doResizeNow=
!0;-1!=navigator.userAgent.indexOf("Android")&&(0==a.windowOrientationScreenSize0&&0==window.orientation&&(a.windowOrientationScreenSize0=f(window).width()),0==a.windowOrientationScreenSize90&&90==window.orientation&&(a.windowOrientationScreenSize90=f(window).height()),0==a.windowOrientationScreenSize_90&&-90==window.orientation&&(a.windowOrientationScreenSize_90=f(window).height()),a.windowOrientationScreenSize0&&0==window.orientation&&f(window).width()>a.windowOrientationScreenSize0&&(doResizeNow=
!1),a.windowOrientationScreenSize90&&90==window.orientation&&f(window).height()>a.windowOrientationScreenSize90&&(doResizeNow=!1),a.windowOrientationScreenSize_90&&-90==window.orientation&&f(window).height()>a.windowOrientationScreenSize_90&&(doResizeNow=!1),0==e.windowWidth&&(doResizeNow=!1,e.windowWidth=f(window).width()));-1!=b&&9==b&&0==e.windowWidth&&(doResizeNow=!1);e.windowWidth==f(window).width()?(doResizeNow=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&
(a.windowCurOrientation=window.orientation,doResizeNow=!0)):e.windowWidth=f(window).width();a.responsive&&doResizeNow&&(!1!==x&&clearTimeout(x),x=setTimeout(function(){var b=a,g=l,k=q,u=C,w=y,B=z,x=F(),E=0;responsiveWidth=c.parent().parent().parent().width();responsiveHeight=c.parent().parent().parent().height();b.responsiveRelativeToBrowser&&(responsiveWidth=f(window).width(),responsiveHeight=f(window).height());b.width100Proc&&(b.width=responsiveWidth);b.height100Proc&&(b.height=responsiveHeight);
if(b.origWidth!=responsiveWidth||b.width100Proc)b.origWidth>responsiveWidth||b.width100Proc?b.width=responsiveWidth:b.width100Proc||(b.width=b.origWidth),b.height100Proc||(b.height=b.width/e.bannerRatio),b.width=parseInt(b.width,10),b.height=parseInt(b.height,10),n.width(b.width),n.height(b.height),d.width(parseInt(b.width-3*b.borderWidth/(b.origWidth/b.width)-b.playlistWidth/(b.origWidth/b.width),10)),d.height(parseInt(b.height-2*b.borderWidth/(b.origWidth/b.width),10)),d.css({left:b.borderWidth/
(b.origWidth/b.width)+"px",top:b.borderWidth/(b.origWidth/b.width)+"px"}),t.width(b.playlistWidth/(b.origWidth/b.width)),t.height(d.height()),r.width(b.playlistWidth/(b.origWidth/b.width)),r.height(d.height()),r.css({top:0,right:-1*(b.borderWidth/(b.origWidth/b.width)+b.playlistWidth/(b.origWidth/b.width))+"px"}),m.width(b.playlistWidth/(b.origWidth/b.width)),m.css("top",b.borderWidth/(b.origWidth/b.width)+"px"),g>b.numberOfThumbsPerScreen&&(0>=b.borderWidth&&(E=h.width()/2),h.height(r.height()-25),
h.css({display:"block",left:Math.floor(b.width-2*b.borderWidth/(b.origWidth/b.width)+(b.borderWidth/(b.origWidth/b.width)-h.width())/2)-E+"px"})),-1!=p.indexOf("ipad")||-1!=p.indexOf("iphone")||-1!=p.indexOf("ipod")||-1!=p.indexOf("webos")||-1!=x&&7>=x?(f("#curBgImgIos",d).attr("src",e.current_imgInside.attr("src")),f("#curBgImgIos",d).width(d.width()),f("#curBgImgIos",d).height(d.height())):-1==x||-1!=x&&9<=x?d.css({"-webkit-background-size":d.width()+"px "+d.height()+"px","-moz-background-size":d.width()+
"px "+d.height()+"px","-o-background-size":d.width()+"px "+d.height()+"px","-ms-background-size":d.width()+"px "+d.height()+"px","background-size":d.width()+"px "+d.height()+"px"}):8==x&&d.css({filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+e.current_imgInside.attr("src")+"',sizingMethod='scale')"}),L(e,b,g,d,A,m,k,t,r,u,w,B),clearTimeout(e.timeoutID),D(1,e,b,g,A,d,k,m,h,v)},300))});f(A[e.current_img_no]).addClass("thumbsHolder_ThumbON");0<a.autoPlay&&1<l&&(a.showCircleTimer&&(e.intervalID=
setInterval(function(){J(e,a)},125)),e.timeoutID=setTimeout(function(){D(1,e,a,l,A,d,q,m,h,v)},1E3*a.autoPlay))})};f.fn.myReverse=[].reverse;f.fn.allinone_bannerWithPlaylist.defaults={skin:"elegant",width:960,height:384,width100Proc:!1,height100Proc:!1,randomizeImages:!1,firstImg:0,numberOfStripes:20,numberOfRows:5,numberOfColumns:10,defaultEffect:"random",effectDuration:.5,autoPlay:4,loop:!0,target:"_blank",showAllControllers:!0,showNavArrows:!0,showOnInitNavArrows:!0,autoHideNavArrows:!0,showThumbs:!0,
borderWidth:15,borderColor:"#e9e9e9",playlistWidth:300,enableTouchScreen:!0,absUrl:"",showCircleTimer:!0,showCircleTimerIE8IE7:!1,circleRadius:10,circleLineWidth:4,circleColor:"#FF0000",circleAlpha:100,behindCircleColor:"#000000",behindCircleAlpha:50,responsive:!1,responsiveRelativeToBrowser:!0,numberOfThumbsPerScreen:0,origWidth:0,origHeight:0,origThumbW:0,origThumbH:0,origThumbImgW:214,origThumbImgH:128,origthumbLeftPadding:0,origthumbRightPadding:0,origthumbTopPadding:0,origthumbBottomPadding:0,
origthumbTitleFont:0,origthumbRegFont:0,origthumbTitleLineHeight:0,origthumbRegLineHeight:0,origthumbsHolder_MarginTop:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);
