/*
 * AllInOne Banner - Carousel v3.5
 *
 * Copyright 2012-2017, LambertGroup
 *
 */


 (function(c){function J(b,a){a.responsive&&(newCss="",-1!=b.css("font-size").lastIndexOf("px")?(fontSize=b.css("font-size").substr(0,b.css("font-size").lastIndexOf("px")),newCss+="font-size:"+fontSize/(a.origWidth/a.width)+"px;"):-1!=b.css("font-size").lastIndexOf("em")&&(fontSize=b.css("font-size").substr(0,b.css("font-size").lastIndexOf("em")),newCss+="font-size:"+fontSize/(a.origWidth/a.width)+"em;"),-1!=b.css("line-height").lastIndexOf("px")?(lineHeight=b.css("line-height").substr(0,b.css("line-height").lastIndexOf("px")),
 newCss+="line-height:"+lineHeight/(a.origWidth/a.width)+"px;"):-1!=b.css("line-height").lastIndexOf("em")&&(lineHeight=b.css("line-height").substr(0,b.css("line-height").lastIndexOf("em")),newCss+="line-height:"+lineHeight/(a.origWidth/a.width)+"em;"),b.wrapInner('<div class="newFS" style="'+newCss+'" />'))}function H(b,a){nowx=(new Date).getTime();b.mouseOverBanner||b.effectIsRunning||!a.showCircleTimer||(b.ctx.clearRect(0,0,b.canvas.width,b.canvas.height),b.ctx.beginPath(),b.ctx.globalAlpha=a.behindCircleAlpha/
 100,b.ctx.arc(a.circleRadius+2*a.circleLineWidth,a.circleRadius+2*a.circleLineWidth,a.circleRadius,0,2*Math.PI,!1),b.ctx.lineWidth=a.circleLineWidth+2,b.ctx.strokeStyle=a.behindCircleColor,b.ctx.stroke(),b.ctx.beginPath(),b.ctx.globalAlpha=a.circleAlpha/100,b.ctx.arc(a.circleRadius+2*a.circleLineWidth,a.circleRadius+2*a.circleLineWidth,a.circleRadius,0,(b.timeElapsed+nowx-b.arcInitialTime)/1E3*2/a.autoPlay*Math.PI,!1),b.ctx.lineWidth=a.circleLineWidth,b.ctx.strokeStyle=a.circleColor,b.ctx.stroke())}
 function B(b,a,f,l,g,n,q,x,e){f.effectIsRunning=!0;a.showCircleTimer&&c(".mycanvas",n).css({display:"none"});"true"==c(g[f.current_img_no]).attr("data-video")&&(c("#contentHolderUnit_"+f.current_img_no,n).html(c(g[f.current_img_no]).html()),a.responsive&&a.width!=a.origWidth&&G(c("#contentHolderUnit_"+f.current_img_no,n),0,a,f));c(l[f.current_img_no]).removeClass("bottomNavButtonON");f.current_img_no=E(f.current_img_no,b,q);"true"!=c(g[f.current_img_no]).attr("data-video")&&x.css("display","none");
 c(l[f.current_img_no]).addClass("bottomNavButtonON");f.currentZ_index=100;f.currentImg=c("#contentHolderUnit_"+f.current_img_no,n);var h=a.contentHolderUnitOrigWidth/(a.origWidth/a.width);var k=a.contentHolderUnitOrigHeight/(a.origWidth/a.width);var p=parseInt((a.width-a.contentHolderUnitOrigWidth/(a.origWidth/a.width))/2,10);var r=parseInt(a.height-a.contentHolderUnitOrigHeight/(a.origWidth/a.width),10)-a.verticalAdjustment/(a.origWidth/a.width);D(f.currentImg,p,r,h,k,1,!1,b,f,a,e,g,q,x,l,n);v=f.current_img_no;
 for(m=1;m<=Math.floor(a.numberOfVisibleItems/2);m++)f.currentZ_index--,v=E(v,-1,q),f.currentImg=c("#contentHolderUnit_"+v,n),f.currentImg.css("z-index",f.currentZ_index),m==Math.floor(a.numberOfVisibleItems/2)&&(1===b?(last_aux_img_no=E(v,-1,q),last_currentImg=c("#contentHolderUnit_"+last_aux_img_no,n),k=a.contentHolderUnitOrigHeight/(a.origWidth/a.width)-2*(m+1)*a.elementsVerticalSpacing/(a.origWidth/a.width),h=parseInt(k*f.aspectOrig,10),p=parseInt((a.width-a.contentHolderUnitOrigWidth/(a.origWidth/
 a.width))/2,10)-(m+1)*a.elementsHorizontalSpacing/(a.origWidth/a.width),r=parseInt(a.height-a.contentHolderUnitOrigHeight/(a.origWidth/a.width),10)-a.verticalAdjustment/(a.origWidth/a.width)+(m+1)*a.elementsVerticalSpacing/(a.origWidth/a.width),D(last_currentImg,p,r,h,k,0,!1,b,f,a,e,g,q,x,l,n)):(k=a.contentHolderUnitOrigHeight/(a.origWidth/a.width)-2*(m+1)*a.elementsVerticalSpacing/(a.origWidth/a.width),parseInt(k*f.aspectOrig,10),G(f.currentImg,m+1,a,f),p=parseInt((a.width-a.contentHolderUnitOrigWidth/
 (a.origWidth/a.width))/2,10)-(m+1)*a.elementsHorizontalSpacing/(a.origWidth/a.width),r=parseInt(a.height-a.contentHolderUnitOrigHeight/(a.origWidth/a.width),10)-a.verticalAdjustment/(a.origWidth/a.width)+(m+1)*a.elementsVerticalSpacing/(a.origWidth/a.width),f.currentImg.css({left:p+"px",top:r+"px",opacity:0}))),f.currentImg.css("display","block"),k=a.contentHolderUnitOrigHeight/(a.origWidth/a.width)-2*m*a.elementsVerticalSpacing/(a.origWidth/a.width),h=parseInt(k*f.aspectOrig,10),p=parseInt((a.width-
 a.contentHolderUnitOrigWidth/(a.origWidth/a.width))/2,10)-m*a.elementsHorizontalSpacing/(a.origWidth/a.width),r=parseInt(a.height-a.contentHolderUnitOrigHeight/(a.origWidth/a.width),10)-a.verticalAdjustment/(a.origWidth/a.width)+m*a.elementsVerticalSpacing/(a.origWidth/a.width),D(f.currentImg,p,r,h,k,1,!1,b,f,a,e,g,q,x,l,n);var v=f.current_img_no;for(m=1;m<=Math.floor(a.numberOfVisibleItems/2);m++)f.currentZ_index--,v=E(v,1,q),f.currentImg=c("#contentHolderUnit_"+v,n),f.currentImg.css("z-index",f.currentZ_index),
 m==Math.floor(a.numberOfVisibleItems/2)&&(1===b?(G(f.currentImg,m+1,a,f),f.currentImg.css({left:parseInt((a.width-a.contentHolderUnitOrigWidth/(a.origWidth/a.width))/2,10)+(a.contentHolderUnitOrigWidth/(a.origWidth/a.width)+(m+1)*a.elementsHorizontalSpacing/(a.origWidth/a.width)-f.currentImg.width())+"px",top:parseInt(a.height-a.contentHolderUnitOrigHeight/(a.origWidth/a.width),10)-a.verticalAdjustment/(a.origWidth/a.width)+(m+1)*a.elementsVerticalSpacing/(a.origWidth/a.width)+"px",opacity:0})):(last_aux_img_no=
 E(v,1,q),last_currentImg=c("#contentHolderUnit_"+last_aux_img_no,n),k=a.contentHolderUnitOrigHeight/(a.origWidth/a.width)-2*(m+1)*a.elementsVerticalSpacing/(a.origWidth/a.width),h=parseInt(k*f.aspectOrig,10),p=parseInt((a.width-a.contentHolderUnitOrigWidth/(a.origWidth/a.width))/2,10)+(a.contentHolderUnitOrigWidth/(a.origWidth/a.width)+(m+1)*a.elementsHorizontalSpacing/(a.origWidth/a.width)-h),r=parseInt(a.height-a.contentHolderUnitOrigHeight/(a.origWidth/a.width),10)-a.verticalAdjustment/(a.origWidth/
 a.width)+(m+1)*a.elementsVerticalSpacing/(a.origWidth/a.width),D(last_currentImg,p,r,h,k,0,!1,b,f,a,e,g,q,x,l,n))),f.currentImg.css("display","block"),k=a.contentHolderUnitOrigHeight/(a.origWidth/a.width)-2*m*a.elementsVerticalSpacing/(a.origWidth/a.width),h=parseInt(k*f.aspectOrig,10),p=parseInt((a.width-a.contentHolderUnitOrigWidth/(a.origWidth/a.width))/2,10)+(a.contentHolderUnitOrigWidth/(a.origWidth/a.width)+m*a.elementsHorizontalSpacing/(a.origWidth/a.width)-h),r=parseInt(a.height-a.contentHolderUnitOrigHeight/
 (a.origWidth/a.width),10)-a.verticalAdjustment/(a.origWidth/a.width)+m*a.elementsVerticalSpacing/(a.origWidth/a.width),m==Math.floor(a.numberOfVisibleItems/2)?D(f.currentImg,p,r,h,k,1,!0,b,f,a,e,g,q,x,l,n):D(f.currentImg,p,r,h,k,1,!1,b,f,a,e,g,q,x,l,n)}function G(b,a,c,l){a=c.contentHolderUnitOrigHeight/(c.origWidth/c.width)-c.elementsVerticalSpacing/(c.origWidth/c.width)*a*2;l=parseInt(a*l.aspectOrig,10);b.css({height:a+"px",width:l+"px"});c.resizeImages&&(imgInside=b.find("img:first"),imgInside.is("img")&&
 imgInside.css({height:a+"px",width:l+"px"}))}function D(b,a,f,l,g,n,q,x,e,h,k,p,r,v,y,t){e.slideIsRunning=!0;k.html(c(p[e.current_img_no]).attr("data-title"));h.responsive&&J(k,h);0===n?b.css("z-index",e.currentZ_index-1):b.css("z-index",e.currentZ_index);b.css("display","block");b.animate({left:a+"px",top:f+"px",width:l+"px",height:g+"px",opacity:n},1E3*h.animationTime,h.easing,function(){if(q){e.slideIsRunning=!1;e.effectIsRunning=!1;e.arcInitialTime=(new Date).getTime();e.timeElapsed=0;h.showCircleTimer&&
 (clearInterval(e.intervalID),e.ctx.clearRect(0,0,e.canvas.width,e.canvas.height),e.ctx.beginPath(),e.ctx.globalAlpha=h.behindCircleAlpha/100,e.ctx.arc(h.circleRadius+2*h.circleLineWidth,h.circleRadius+2*h.circleLineWidth,h.circleRadius,0,2*Math.PI,!1),e.ctx.lineWidth=h.circleLineWidth+2,e.ctx.strokeStyle=h.behindCircleColor,e.ctx.stroke(),e.ctx.beginPath(),e.ctx.globalAlpha=h.circleAlpha/100,e.ctx.arc(h.circleRadius+2*h.circleLineWidth,h.circleRadius+2*h.circleLineWidth,h.circleRadius,0,0,!1),e.ctx.lineWidth=
 h.circleLineWidth,e.ctx.strokeStyle=h.circleColor,e.ctx.stroke(),e.intervalID=setInterval(function(){H(e,h)},125),cLeftPos=c("#contentHolderUnit_"+e.current_img_no,t).css("left"),cTopPos=c("#contentHolderUnit_"+e.current_img_no,t).css("top"),c(".mycanvas",t).css({display:"block",left:parseInt(cLeftPos.substr(0,cLeftPos.lastIndexOf("px")),10)+parseInt(h.circleLeftPositionCorrection/(h.origWidth/h.width),10)+"px",top:parseInt(cTopPos.substr(0,cTopPos.lastIndexOf("px")),10)+parseInt(h.circleTopPositionCorrection/
 (h.origWidth/h.width),10)+"px"}));"true"==c(p[e.current_img_no]).attr("data-video")&&v.css("display","block");if(0<h.autoPlay&&1<r&&!e.mouseOverBanner&&!e.fastForwardRunning||e.current_img_no!=e.img_no_where_to_stop&&e.fastForwardRunning)clearTimeout(e.timeoutID),e.timeoutID=setTimeout(function(){B(x,h,e,y,p,t,r,v,k)},1E3*h.autoPlay);e.current_img_no==e.img_no_where_to_stop&&e.fastForwardRunning&&(e.fastForwardRunning=!1,h.animationTime=e.animationTimeOrig,h.autoPlay=e.autoPlayOrig)}});h.resizeImages&&
 (imgInside=b.find("img:first"),imgInside.is("img")&&imgInside.animate({width:l+"px",height:g+"px"},1E3*h.animationTime,h.easing,function(){}))}function E(b,a,c){return b+a>=c?0:0>b+a?c-1:b+a}function K(b,a,c,l,g,n,q,x,e){-1===c.current_img_no-b?B(1,a,c,l,g,n,q,x,e):1===c.current_img_no-b?B(-1,a,c,l,g,n,q,x,e):(c.fastForwardRunning=!0,a.animationTime=.4,a.autoPlay=.1,c.img_no_where_to_stop=b,c.current_img_no<b?b-c.current_img_no<q-b+c.current_img_no?B(1,a,c,l,g,n,q,x,e):B(-1,a,c,l,g,n,q,x,e):c.current_img_no>
 b&&(c.current_img_no-b<q-c.current_img_no+b?B(-1,a,c,l,g,n,q,x,e):B(1,a,c,l,g,n,q,x,e)))}function N(b,a,f,l,g,n,q,x,e,h,k,p,r,v,y,t,u){v.css("display","none");responsiveWidth=g.parent().parent().width();responsiveHeight=g.parent().parent().height();a.responsiveRelativeToBrowser&&(responsiveWidth=c(window).width(),responsiveHeight=c(window).height());a.width100Proc&&(a.width=responsiveWidth);a.height100Proc&&(a.height=responsiveHeight);if(a.origWidth!=responsiveWidth||a.width100Proc)a.origWidth>responsiveWidth||
 a.width100Proc?a.width=responsiveWidth:a.width100Proc||(a.width=a.origWidth),a.height100Proc||(a.height=a.width/b.bannerRatio),a.width=parseInt(a.width,10),a.height=parseInt(a.height,10),q.width(a.width),q.height(a.height),t.width(a.width),t.height(a.height),n.css("margin-top",parseInt((a.height-x.height())/2,10)+a.nextPrevMarginTop/(a.origWidth/a.width)+"px"),e.css("left",parseInt((q.width()-e.width())/2,10)+"px"),h.css("left",parseInt(e.css("left").substring(0,e.css("left").length-2),10)-h.width()+
 "px"),k.css("left",parseInt(e.css("left").substring(0,e.css("left").length-2),10)+e.width()+parseInt(p.css("padding-left").substring(0,p.css("padding-left").length-2),10)+"px"),v.css({left:parseInt((a.width-v.width())/2,10)+"px",top:parseInt(a.height-a.contentHolderUnitOrigHeight/(a.origWidth/a.width),10)+parseInt((a.contentHolderUnitOrigHeight/(a.origWidth/a.width)-v.height())/2,10)-parseInt(a.verticalAdjustment/(a.origWidth/a.width),10)+"px","margin-top":a.playMovieMarginTop/(a.origWidth/a.width)}),
 y.css("top",parseInt(a.elementOrigTop/(a.origWidth/a.width),10)),clearTimeout(b.timeoutID),clearInterval(b.intervalID),b.timeoutID=setTimeout(function(){B(1,a,b,r,l,q,f,v,y)},.1)}function L(){var b=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(b=parseFloat(RegExp.$1));return parseInt(b,10)}var F=!1;c.fn.allinone_carousel=function(b){b=c.extend({},c.fn.allinone_carousel.defaults,b);return this.each(function(){var a=c(this);responsiveWidth=
 a.parent().width();responsiveHeight=a.parent().height();b.responsiveRelativeToBrowser&&(responsiveWidth=c(window).width(),responsiveHeight=c(window).height());b.origWidth=b.width;b.width100Proc&&(b.width=responsiveWidth);b.origHeight=b.height;b.height100Proc&&(b.height=responsiveHeight);b.responsive&&(b.origWidth!=responsiveWidth||b.width100Proc)&&(b.width=b.origWidth>responsiveWidth||b.width100Proc?responsiveWidth:b.origWidth,b.height100Proc||(b.height=b.width/(b.origWidth/b.origHeight)));b.width=
 parseInt(b.width,10);b.height=parseInt(b.height,10);var f=c("<div></div>").addClass("allinone_carousel").addClass(b.skin),l=c('<div class="bannerControls">   <div class="leftNav"></div>   <div class="rightNav"></div>    </div>  <div class="contentHolder"></div>   <div class="elementTitle"></div>\t<div class="playOver"></div>  <canvas class="mycanvas"></canvas>');a.wrap(f);a.after(l);var g=a.parent(".allinone_carousel"),l=c(".bannerControls",g),n=c(".contentHolder",g),f=c('<div class="bottomNavLeft"></div>'),
 q=c('<div class="bottomNav"></div>'),x=c('<div class="bottomNavRight"></div>');a.after(f);a.after(q);a.after(x);b.showAllControllers||l.css("display","none");var e=c(".leftNav",g),h=c(".rightNav",g);e.css("display","none");h.css("display","none");b.showNavArrows&&b.showOnInitNavArrows&&(e.css("display","block"),h.css("display","block"));var k=c(".bottomNav",g),p=c(".bottomNavLeft",g),r=c(".bottomNavRight",g),v;k.css("display","block");p.css("display","block");r.css("display","block");k.css({bottom:b.bottomNavMarginBottom+
 "px",top:"auto"});p.css({bottom:b.bottomNavMarginBottom+"px",top:"auto"});r.css({bottom:b.bottomNavMarginBottom+"px",top:"auto"});b.showBottomNav||(k.css("display","none"),p.css("display","none"),r.css("display","none"));b.showOnInitBottomNav||(k.css("left","-5000px"),p.css("left","-5000px"),r.css("left","-5000px"));var y=c(".elementTitle",g);b.showElementTitle||y.css("display","none");b.elementOrigTop=parseInt(y.css("top").substr(0,y.css("top").lastIndexOf("px")),10);y.css("top",parseInt(b.elementOrigTop/
 (b.origWidth/b.width),10));var t=c(".playOver",g),f=L(),u=0,d={current_img_no:0,currentImg:0,currentZ_index:101,slideIsRunning:!1,effectIsRunning:!1,mouseOverBanner:!1,fastForwardRunning:!1,isVideoPlaying:!1,img_no_where_to_stop:0,aspectOrig:0,animationTimeOrig:b.animationTime,autoPlayOrig:b.autoPlay,timeoutID:"",intervalID:"",arcInitialTime:(new Date).getTime(),timeElapsed:0,windowWidth:0,canvas:"",ctx:"",bannerRatio:b.origWidth/b.origHeight},D;d.canvas=c(".mycanvas",g)[0];d.canvas.width=2*b.circleRadius+
 4*b.circleLineWidth;d.canvas.height=2*b.circleRadius+4*b.circleLineWidth;-1!=f&&9>f&&(b.showCircleTimer=!1);b.showCircleTimer&&(d.ctx=d.canvas.getContext("2d"));g.width(b.width);g.height(b.height);n.width(b.width);n.height(b.height);l.css("margin-top",parseInt((b.height-e.height())/2,10)+b.nextPrevMarginTop/(b.origWidth/b.width)+"px");var w=a.find("ul:first").children();b.numberOfVisibleItems>a.find("ul:first li").length&&(b.numberOfVisibleItems=a.find("ul:first li").length);b.numberOfVisibleItems%
 2||b.numberOfVisibleItems--;var C,E=0,M=0;w.each(function(){d.currentImg=c(this);d.currentImg.is("li")||(d.currentImg=d.currentImg.find("li:first"));d.currentImg.is("li")&&(u++,z=c('<div class="contentHolderUnit" rel="'+(u-1)+'" id="contentHolderUnit_'+(u-1)+'">'+d.currentImg.html()+"</div>"),n.append(z),z.css("display","none"),0===b.contentHolderUnitOrigWidth&&(b.contentHolderUnitOrigWidth=z.width(),b.contentHolderUnitOrigHeight=z.height(),d.aspectOrig=b.contentHolderUnitOrigWidth/b.contentHolderUnitOrigHeight),
 G(z,0,b,d),z.css({left:parseInt((b.width-z.width())/2,10)+"px",top:parseInt(b.height-z.height(),10)-b.verticalAdjustment/(b.origWidth/b.width)+"px"}),1==u?(z.css({left:parseInt((b.width-z.width())/2,10)+"px",top:parseInt(b.height-z.height(),10)-b.verticalAdjustment/(b.origWidth/b.width)+"px","z-index":d.currentZ_index,display:"block"}),"true"==c(w[d.current_img_no]).attr("data-video")&&t.css("display","block")):u<=Math.ceil(b.numberOfVisibleItems/2)&&(d.currentZ_index--,G(z,u-1,b,d),z.css({left:parseInt((b.width-
 b.contentHolderUnitOrigWidth/(b.origWidth/b.width))/2,10)+(b.contentHolderUnitOrigWidth/(b.origWidth/b.width)+(u-1)*b.elementsHorizontalSpacing/(b.origWidth/b.width)-z.width())+"px",top:parseInt(b.height-b.contentHolderUnitOrigHeight/(b.origWidth/b.width),10)-b.verticalAdjustment/(b.origWidth/b.width)+(u-1)*b.elementsVerticalSpacing/(b.origWidth/b.width)+"px","z-index":d.currentZ_index,display:"block"})),C=c('<div class="bottomNavButtonOFF" rel="'+(u-1)+'"></div>'),k.append(C),E+=parseInt(C.css("padding-left").substring(0,
 C.css("padding-left").length-2),10)+C.width(),M=parseInt((k.height()-parseInt(C.css("height").substring(0,C.css("height").length-2)))/2,10),C.css("margin-top",M+"px"))});t.css({left:parseInt((b.width-t.width())/2,10)+"px",top:parseInt(b.height-b.contentHolderUnitOrigHeight/(b.origWidth/b.width),10)+parseInt((b.contentHolderUnitOrigHeight/(b.origWidth/b.width)-t.height())/2,10)-parseInt(b.verticalAdjustment/(b.origWidth/b.width),10)+"px","margin-top":b.playMovieMarginTop/(b.origWidth/b.width)});b.showCircleTimer&&
 (cLeftPos=c("#contentHolderUnit_"+d.current_img_no,g).css("left"),cTopPos=c("#contentHolderUnit_"+d.current_img_no,g).css("top"),c(".mycanvas",g).css({left:parseInt(cLeftPos.substr(0,cLeftPos.lastIndexOf("px")),10)+parseInt(b.circleLeftPositionCorrection/(b.origWidth/b.width),10)+"px",top:parseInt(cTopPos.substr(0,cTopPos.lastIndexOf("px")),10)+parseInt(b.circleTopPositionCorrection/(b.origWidth/b.width),10)+"px"}));d.currentZ_index=100;for(m=1;m<=Math.floor(b.numberOfVisibleItems/2);m++)d.currentZ_index--,
 G(c("#contentHolderUnit_"+(u-m),g),m,b,d),c("#contentHolderUnit_"+(u-m),g).css({left:parseInt((b.width-b.contentHolderUnitOrigWidth/(b.origWidth/b.width))/2,10)-m*b.elementsHorizontalSpacing/(b.origWidth/b.width)+"px",top:parseInt(b.height-b.contentHolderUnitOrigHeight/(b.origWidth/b.width),10)-b.verticalAdjustment/(b.origWidth/b.width)+m*b.elementsVerticalSpacing/(b.origWidth/b.width)+"px","z-index":d.currentZ_index,display:"block"});y.html(c(w[0]).attr("data-title"));b.responsive&&J(y,b);k.width(E);
 b.showOnInitBottomNav&&(k.css("left",parseInt((g.width()-E)/2,10)+"px"),p.css("left",parseInt(k.css("left").substring(0,k.css("left").length-2),10)-p.width()+"px"),r.css("left",parseInt(k.css("left").substring(0,k.css("left").length-2),10)+k.width()+parseInt(C.css("padding-left").substring(0,C.css("padding-left").length-2),10)+"px"));c("iframe",g).each(function(){var a=c(this).attr("src"),b="?wmode=transparent";-1!=a.indexOf("?")&&(b="&wmode=transparent");c(this).attr("src",a+b)});d.current_img_no=
 0;d.currentImg=c(w[d.current_img_no]);g.mouseenter(function(){d.mouseOverBanner=!0;d.effectIsRunning||(clearTimeout(d.timeoutID),nowx=(new Date).getTime(),d.timeElapsed+=nowx-d.arcInitialTime,b.autoHideNavArrows&&b.showNavArrows&&(e.css("display","block"),h.css("display","block")),b.autoHideBottomNav&&b.showBottomNav&&(k.css({display:"block",left:parseInt((g.width()-E)/2,10)+"px"}),p.css({display:"block",left:parseInt(k.css("left").substring(0,k.css("left").length-2),10)-p.width()+"px"}),r.css({display:"block",
 left:parseInt(k.css("left").substring(0,k.css("left").length-2),10)+k.width()+parseInt(C.css("padding-left").substring(0,C.css("padding-left").length-2),10)+"px"})))});g.mouseleave(function(){d.mouseOverBanner=!1;if(!d.effectIsRunning&&(nowx=(new Date).getTime(),b.autoHideNavArrows&&b.showNavArrows&&(e.css("display","none"),h.css("display","none")),b.autoHideBottomNav&&b.showBottomNav&&(k.css("display","none"),p.css("display","none"),r.css("display","none")),0<b.autoPlay&&1<u&&!d.fastForwardRunning&&
 !d.isVideoPlaying)){clearTimeout(d.timeoutID);d.arcInitialTime=(new Date).getTime();var a=parseInt(1E3*b.autoPlay-(d.timeElapsed+nowx-d.arcInitialTime),10);d.timeoutID=setTimeout(function(){B(1,b,d,A,w,g,u,t,y)},a)}});var z=c(".contentHolderUnit",g);z.click(function(){if(!d.slideIsRunning&&!d.fastForwardRunning){var a=c(this).attr("rel");a!=d.current_img_no?(d.isVideoPlaying=!1,c(A[d.current_img_no]).removeClass("bottomNavButtonON"),K(parseInt(a,10),b,d,A,w,g,u,t,y)):"true"==c(w[d.current_img_no]).attr("data-video")?
 (t.css("display","none"),D=c(this).find("img:first"),D.css("display","none"),d.isVideoPlaying=!0):void 0==c(w[d.current_img_no]).attr("data-link")||""==c(w[d.current_img_no]).attr("data-link")||d.effectIsRunning||F||(a=b.target,void 0!=c(w[d.current_img_no]).attr("data-target")&&""!=c(w[d.current_img_no]).attr("data-target")&&(a=c(w[d.current_img_no]).attr("data-target")),"_blank"==a?window.open(c(w[d.current_img_no]).attr("data-link")):window.location=c(w[d.current_img_no]).attr("data-link"))}});
 t.click(function(){b.showCircleTimer&&c(".mycanvas",g).css({display:"none"});t.css("display","none");D=c("#contentHolderUnit_"+d.current_img_no,g).find("img:first");D.css("display","none");d.isVideoPlaying=!0});e.click(function(){F=!0;d.slideIsRunning||d.fastForwardRunning||(d.isVideoPlaying=!1,clearTimeout(d.timeoutID),B(-1,b,d,A,w,g,u,t,y))});e.mouseout(function(){F=!1});h.click(function(){F=!0;d.slideIsRunning||d.fastForwardRunning||(d.isVideoPlaying=!1,clearTimeout(d.timeoutID),B(1,b,d,A,w,g,
 u,t,y))});h.mouseout(function(){F=!1});var A=c(".bottomNavButtonOFF",g);A.click(function(){F=!0;if(!d.slideIsRunning&&!d.fastForwardRunning){var a=c(this).attr("rel");a!=d.current_img_no&&(d.isVideoPlaying=!1,c(A[d.current_img_no]).removeClass("bottomNavButtonON"),K(parseInt(a,10),b,d,A,w,g,u,t,y))}});A.mouseout(function(){F=!1});A.mouseenter(function(){var a=c(this),d=a.attr("rel");b.showPreviewThumbs&&(v=c('<div class="bottomOverThumb"></div>'),a.append(v),d=c(w[d]).attr("data-bottom-thumb"),v.html('<img src="'+
 d+'">'));a.addClass("bottomNavButtonON")});A.mouseleave(function(){var a=c(this),e=a.attr("rel");b.showPreviewThumbs&&v.remove();d.current_img_no!=e&&a.removeClass("bottomNavButtonON")});b.enableTouchScreen&&g.swipe({swipe:function(a,c,e,f,h){d.effectIsRunning||B("right"==c?-1:1,b,d,A,w,g,u,t,y)}});var I=!1;c(window).resize(function(){var f=L();doResizeNow=!0;-1!=navigator.userAgent.indexOf("Android")&&(0==b.windowOrientationScreenSize0&&0==window.orientation&&(b.windowOrientationScreenSize0=c(window).width()),
 0==b.windowOrientationScreenSize90&&90==window.orientation&&(b.windowOrientationScreenSize90=c(window).height()),0==b.windowOrientationScreenSize_90&&-90==window.orientation&&(b.windowOrientationScreenSize_90=c(window).height()),b.windowOrientationScreenSize0&&0==window.orientation&&c(window).width()>b.windowOrientationScreenSize0&&(doResizeNow=!1),b.windowOrientationScreenSize90&&90==window.orientation&&c(window).height()>b.windowOrientationScreenSize90&&(doResizeNow=!1),b.windowOrientationScreenSize_90&&
 -90==window.orientation&&c(window).height()>b.windowOrientationScreenSize_90&&(doResizeNow=!1),0==d.windowWidth&&(doResizeNow=!1,d.windowWidth=c(window).width()));-1!=f&&9==f&&0==d.windowWidth&&(doResizeNow=!1);d.windowWidth==c(window).width()?(doResizeNow=!1,b.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(b.windowCurOrientation=window.orientation,doResizeNow=!0)):d.windowWidth=c(window).width();b.responsive&&doResizeNow&&(!1!==I&&clearTimeout(I),I=setTimeout(function(){N(d,
 b,u,w,a,l,g,e,k,p,r,C,A,t,y,n,z)},300))});c(A[d.current_img_no]).addClass("bottomNavButtonON");f=g.find("img:first");f[0].complete?(c(".myloader",g).css("display","none"),0<b.autoPlay&&1<u&&(b.showCircleTimer&&(d.arcInitialTime=(new Date).getTime(),d.timeElapsed=0,d.intervalID=setInterval(function(){H(d,b)},125)),d.timeoutID=setTimeout(function(){B(1,b,d,A,w,g,u,t,y)},1E3*b.autoPlay))):f.load(function(){c(".myloader",g).css("display","none");0<b.autoPlay&&1<u&&(b.showCircleTimer&&(d.arcInitialTime=
 (new Date).getTime(),d.timeElapsed=0,d.intervalID=setInterval(function(){H(d,b)},125)),d.timeoutID=setTimeout(function(){B(1,b,d,A,w,g,u,t,y)},1E3*b.autoPlay))})})};c.fn.allinone_carousel.defaults={skin:"attractive",width:960,height:384,width100Proc:!1,height100Proc:!1,autoPlay:4,numberOfVisibleItems:7,elementsHorizontalSpacing:120,elementsVerticalSpacing:20,verticalAdjustment:0,animationTime:.8,easing:"easeOutQuad",resizeImages:!0,target:"_blank",showElementTitle:!0,showAllControllers:!0,showNavArrows:!0,
 showOnInitNavArrows:!0,autoHideNavArrows:!0,showBottomNav:!0,showOnInitBottomNav:!0,autoHideBottomNav:!0,showPreviewThumbs:!0,nextPrevMarginTop:0,playMovieMarginTop:0,enableTouchScreen:!0,absUrl:"",showCircleTimer:!0,showCircleTimerIE8IE7:!1,circleRadius:10,circleLineWidth:4,circleColor:"#FF0000",circleAlpha:100,behindCircleColor:"#000000",behindCircleAlpha:50,circleLeftPositionCorrection:3,circleTopPositionCorrection:3,responsive:!1,responsiveRelativeToBrowser:!0,bottomNavMarginBottom:0,origWidth:0,
 origHeight:0,contentHolderUnitOrigWidth:0,contentHolderUnitOrigHeight:0,elementOrigTop:0,origthumbsHolder_MarginTop:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);
